### ISSUE TITLE
REPORT TONASE

### ISSUE THREAD

**Issue by bening14** [solusi-cipta-media/bank-sampah-kalisari#21]
![image](https://user-images.githubusercontent.com/55275901/135976527-b84c5940-4565-4563-aeaf-f10083392447.png)

Pada menu LAPORAN ditambah sub menu REPORT TONASE, isinya adalah grafik bar jumlah KG dari transaksi setor sampah dan jual sampah setiap bulan, jadi data yang ditampilkan adalah jumlah tonase/KG dalam tiap bulan

Angka yang di dapat adalah 

RUMUS = field sum(jumlah) tbl_detail_setor_sampah - field sum(jumlah) tbl_detail_jual_sampah

**Comment by nggepe** [comment]
ini dibuat per bulan pak?
